### ISSUE TITLE
Cleaning up 

### ISSUE THREAD

**Issue by cslotboom** [u-anurag/OpenSeesPy#27]
With #26, we should have a working animation with a slider. I feel like the work so far can be categorized into two areas:

1. A suite of tools for visualizing displacements
2. An output database for storing and retrieving model information.

Before we get too crazy with adding features, my feeling is that the code should be cleaned up a little bit and tested before we formally doing any release.
Some of the files and functions could definitely be consolidated.

We might also consider checking in with zhuminjie to see if he has any comments for us before a release.
I believe they were using pytest on the main branch to test their functions, it may be a good idea to create a suite of tests that encompasses important functions.

**Comment by u-anurag** [comment]
Don't start cleaning up yet. I have to push a major change in the plotting function, including changing some variable names, so they can use internal database functions and streamline the visualization from the ODB and the active model at the same time. You might have to incorporate some of these changes in the animation library. 

1) [Not for this release] I had this thought, what if we return a final plot in the `plot_model()` function so it can be used in an animation. When the user calls the plot_model(), it just displays the model. The animation function can also call the plot_model() to update the plot based on the displaced nodes. There could be some input arguments to the plot_model() that are not available to the users. 

2) Did you check the Matplotlib slider widget in Jupyter or IPython console?

3) You can start putting the list of items that require cleaning up in this thread.

**Comment by cslotboom** [comment]
Sounds good, I'll won't plan on making any changes for a bit.

> [Not for this release] I had this thought, what if we return a final plot in the plot_model() function so it can be used in an animation. When the user calls the plot_model(), it just displays the model. The animation function can also call the plot_model() to update the plot based on the displaced nodes. There could be some input arguments to the plot_model() that are not available to the users.

There might be a way, but I think it would be challenging to use plot_model() to update the plot. Right now the animation function only updates the xyz coordinants of existing objects, it doesn't make any new ones. 
For example:
```
EqfigLines[jj].set_xdata(coords_x)
EqfigLines[jj].set_ydata(coords_y)
```
If we call plot_model(), we are making new objects, which probably has more overhead.

The best way I could find to reuse functions is with something like the _plotEle_3D - this makes the base elements which are used in the animation, and could potentially make the plot elements in plot_model().


> Did you check the Matplotlib slider widget in Jupyter or IPython console?

Yes, but it should maybe be formalized in a test or example.

**Comment by cslotboom** [comment]
Hey, so some thoughts on cleaning are here:

**__init__**
Is there a way we can import all functions using init? This might be cleaner than separately calling different modules

**Tests:**
- Consider having a set of manual tests that developers can use to trouble shoot, as well as a suite of PyTest functions to confirm the important functions are working.


**For get_rendering:**
plot_model/plot_modeshape/plot_deformedshape
- Consider standardizing the element creating loop to cut down on code. right now all three functions use a very similar loop. sample_plot_model could be a template for this.
- Consider standardizing the view setting functions to cut down on code.

SaveOBD /ReadODB 
- SaveOBD and ReadODB returns all values by default, it might be worth adding some functionality that let's the users decide what they want to be saved/returned. For a big model this could be a lot of unnecessary data.
- consider separating ReadODB into seperate functions i.e. _readODBForces, _readOBDStrains, etc. I think it might be confusing to return certain values sometimes, and different values other times

i.e.
```
	if len(argv)>=2:
		return nodes, elements, NodeDisp, Reaction, EleForce
	else:
		return nodes, elements
```


**For the get Animation function:**
- initializeFig, _setStandardViewport, _plotEle_2D, _plotEle_3D   ->   Internal plot functions
- getDispAnimationSlider  ->  get_rendering
- **sample_plot_model** -> use as a template to consolidate  plot_model/plot_modeshape/plot_deformedshape, then remove


**For the fibre functions**
- Create a procedure to save fibre data to the output database.
- plotFiberResponse -> get_rendering
- animateFiber2D - >get_rendering
- animateFiber2DFile -> Consolidate with animateFiber2D

**Comment by u-anurag** [comment]
Good points! 
* init: Are you talking about the users? Users only import Get_Rendering. Also, Get_Rendering imports all other internal libraries so users don't need to call them. If you are talking about importing multiple libraries in Get_Rndering, I think we should keep it like this. It is easy to keep track of things this way.
* Tests: Agree! We can create a separate Test Examples folder for developers. One test example for each type of element (example: PortalFrame3D.py for beam-column elements, RCshearwall.py for shell elements etc.) with all plotting commands (from active model and ODB) along with createODB() in it. PyTest can be an automated system.
* Standardizing Get_Rendering loops: I agree on that. I am not in a hurry in doing so since our aim is to also include plot_eleStress() and plot_eleStrain() functions in the next release. The best would be if the standardized internal plotting functions and loops can also handle the plotting of stresses/strains and element forces. In order to do that, first, we should aim to successfully implement these new functions and see how best we can standardize them. In my opinion, these functions can stay as they are for this release. 
* createODB(): Yes, we could let users provide arguments to save selective data. 
* readODB() : I have second thoughts about the use of this function. I created a new internal database function `_readNodeDispData(Model,LoadCase)` to be called by plot_deformedshape() function. In this way, we don't need to use additional memory to store the data the command is not using. Better we could just create more internal functions like this for other plotting commands, i.e. plot_eleStress() etc.
* animate_deformedshape: As mentioned above, we should wait before consolidating the function. For now, let's try to call animation function from Get_Rendering library.
* Fiber response: How do you get the location of all the fibers in that particular section? Also, could you post an image of how the output looks like? 

Cleaning up the code is a long term process. Let's make sure the commands we have developed so far work for users on all the platforms. Let's aim for next Monday to test and push all the new code to the official repo. Do you think you can finish testing the animation functions by then? Once, Minjie releases the next minor version, we'll add documentation for these commands.

**Comment by cslotboom** [comment]
- Makes sense in terms of Get_Rendering
- Tests: Sounds good. I would be happy to oversee this.
- Okay, that makes sense. Long term, it also might make sense to move to an objected oriented framework.
- createODB: I'd be happy to give the users options for selective data handling.
- readODB: Agreed, I really like the new function, I think having more internal functions makes sense instead of readODB.
- We can use the fibre command "fibreData" in the recorder. Also see [this ](https://opensees.berkeley.edu/community/viewtopic.php?f=12&t=66954&sid=1ae0beea4615c10378e1f8e419523259) thread.
`'-ele', eleNumber, 'section', str(sectionNumber), 'fiberData'`


Outputs look like this - here we have fibre stress v.s. fibre location for all fibres. There is a slider to let the user chose the frame they want to see.



![Capture](https://user-images.githubusercontent.com/50510141/86328949-5de92500-bbfa-11ea-998b-df0c76648a2e.PNG)
![Capture2 ](https://user-images.githubusercontent.com/50510141/86328950-5de92500-bbfa-11ea-84c1-24fe7c73bbdf.PNG)

Monday if fine. Let's make a list of the goals for that release then go from there.

**Comment by cslotboom** [comment]
Can this be closed?

I think the only thing that we haven't really done is standardizing the three plot functions i.e.

> For get_rendering:
> plot_model/plot_modeshape/plot_deformedshape
> 
>     Consider standardizing the element creating loop to cut down on code. right now all three functions use a very similar loop. sample_plot_model could be a template for this.


I think this is probably worth standardizing the functions at some point. Maybe we can close this and make that it's own issue?

**Comment by u-anurag** [comment]
We can close this one. I am working on plot_stress() and plot_strain(). I was planning on moving to standardization after I implement these two functions so we know the best way to do that. It has been slow on my end but I'll do it soon.
